### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/rc_issues#1]
@jblachly if you run this test program you can see what I previously described. I am thinking of posting on the dlang forums linking this repo, asking if anyone knows about this behavior.

**Comment by jblachly** [comment]
We should be using `std.typecons.RefCounted` 

https://dlang.org/library/std/typecons/ref_counted.html

🤦🤦🤦

**Comment by charlesgregory** [comment]
Yes I agree, I have a new pull request on `dhtslib` that now uses `refcounted`. It's clear now that these issues are due to my faulty reference counting implementation so I will close.
